//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 11:33:38 AM IST 
//


package almarRestModels;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.exlibrisgroup.almarestmodels.representation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserRequest_QNAME = new QName("", "user_request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.exlibrisgroup.almarestmodels.representation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourceSharing }
     * 
     */
    public ResourceSharing createResourceSharing() {
        return new ResourceSharing();
    }

    /**
     * Create an instance of {@link UserRequest }
     * 
     */
    public UserRequest createUserRequest() {
        return new UserRequest();
    }

    /**
     * Create an instance of {@link ResourceSharing.Status }
     * 
     */
    public ResourceSharing.Status createResourceSharingStatus() {
        return new ResourceSharing.Status();
    }

    /**
     * Create an instance of {@link UserRequest.RequestSubType }
     * 
     */
    public UserRequest.RequestSubType createUserRequestRequestSubType() {
        return new UserRequest.RequestSubType();
    }

    /**
     * Create an instance of {@link UserRequest.TargetDestination }
     * 
     */
    public UserRequest.TargetDestination createUserRequestTargetDestination() {
        return new UserRequest.TargetDestination();
    }

    /**
     * Create an instance of {@link UserRequest.MaterialType }
     * 
     */
    public UserRequest.MaterialType createUserRequestMaterialType() {
        return new UserRequest.MaterialType();
    }

    /**
     * Create an instance of {@link UserRequest.DestinationLocation }
     * 
     */
    public UserRequest.DestinationLocation createUserRequestDestinationLocation() {
        return new UserRequest.DestinationLocation();
    }

    /**
     * Create an instance of {@link UserRequest.CallNumberType }
     * 
     */
    public UserRequest.CallNumberType createUserRequestCallNumberType() {
        return new UserRequest.CallNumberType();
    }

    /**
     * Create an instance of {@link UserRequest.ItemPolicy }
     * 
     */
    public UserRequest.ItemPolicy createUserRequestItemPolicy() {
        return new UserRequest.ItemPolicy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_request")
    public JAXBElement<UserRequest> createUserRequest(UserRequest value) {
        return new JAXBElement<UserRequest>(_UserRequest_QNAME, UserRequest.class, null, value);
    }

}
