//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 11:33:38 AM IST 
//


package almarRestModels;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pickup_location_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pickup_location_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LIBRARY"/>
 *     &lt;enumeration value="CIRCULATION_DESK"/>
 *     &lt;enumeration value="USER_WORK_ADDRESS"/>
 *     &lt;enumeration value="USER_HOME_ADDRESS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pickup_location_types")
@XmlEnum
public enum PickupLocationTypes {

    LIBRARY,
    CIRCULATION_DESK,
    USER_WORK_ADDRESS,
    USER_HOME_ADDRESS;

    public String value() {
        return name();
    }

    public static PickupLocationTypes fromValue(String v) {
        return valueOf(v);
    }

}
