//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.18 at 11:33:38 AM IST 
//


package almarRestModels;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="request_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BOOKING"/>
 *     &lt;enumeration value="DIGITIZATION"/>
 *     &lt;enumeration value="HOLD"/>
 *     &lt;enumeration value="MOVE"/>
 *     &lt;enumeration value="WORK_ORDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "request_types")
@XmlEnum
public enum RequestTypes {

    BOOKING,
    DIGITIZATION,
    HOLD,
    MOVE,
    WORK_ORDER;

    public String value() {
        return name();
    }

    public static RequestTypes fromValue(String v) {
        return valueOf(v);
    }

}
